#!/usr/bin/env bash
# Dump all MySQL databases to the backup file and
# create a compressed archive of the backup file

mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf $(date +%d-%m-%Y).tar.gz backup.sql
