#!/usr/bin/env bash

# Get the current date
date=$(date +%d-%m-%Y)

# Set the filename for the backup
filename="backup.sql"

# Get the MySQL password from the command line argument
password="$1"

# Dump all MySQL databases to the backup file
mysqldump -u root -p$password --all-databases > $filename

# Create a compressed archive of the backup file
tar -czvf $date.tar.gz $filename

# Remove the backup file
rm $filename
