#!/usr/bin/env bash

# Change ownership of Nginx directories to the nginx user
chown -R nginx:nginx /var/www/html /var/log/nginx /var/lib/nginx /etc/nginx

# Modify Nginx configuration to run as nginx user and listen on port 8080

sed -i 's/^user .*/user nginx;\n/' /etc/nginx/nginx.conf
sed -i 's/^listen 80 default_server;/listen 8080 default_server;\n/' /etc/nginx/sites-available/default

# Reload Nginx configuration

nginx -t && systemctl reload nginx
