#!/usr/bin/env bash

# Change ownership of Nginx directories to the nginx user
chmod 644 /etc/nginx/nginx.conf
# Modify Nginx configuration to run as nginx user and listen on port 8080
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
# To stop apache from interfering kill process
pkill apache2
# restart the nginx service with the new nginx user
su nginx -s /bin/bash -c 'service nginx restart'
