#!/usr/bin/env bash
# shorter commands and removes semicolons and && operators
chown -R nginx:nginx /var/{www/html,log/nginx,lib/nginx,etc/nginx}
sed -i 's/^user .*/user nginx\n/' /etc/nginx/nginx.conf
sed -i 's/^listen 80 default_server;/listen 8080 default_server\n/' /etc/nginx/sites-available/default
systemctl reload nginx
